### ISSUE TITLE
Error in console after adding moleculer-http-client as mixins

### ISSUE THREAD

**Issue by yogesh-rs** [moleculerjs/moleculer-http-client#5]
1. require `const HTTPClientService = require("moleculer-http-client");`
2. `mixins: [HTTPClientService],`  // this line throws an error in console
3. Run `npm run dev`

--

Result : 
```
Request error! TypeError : Converting circular structure to JSON
    --> starting at object with constructor 'ServiceBroker'
    |     property 'services' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Service'
    --- property 'broker' closes the circle
 TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ServiceBroker'
    |     property 'services' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Service'
    --- property 'broker' closes the circle
    at JSON.stringify (<anonymous>)
    at Service.encodeResponse (/Volumes/Boskysoft/work-hdd/recrutiment-smart/play/nodejs/moleculer-js/http-client/node_modules/moleculer-web/src/index.js:649:16)
    at Service.sendResponse (/Volumes/Boskysoft/work-hdd/recrutiment-smart/play/nodejs/moleculer-js/http-client/node_modules/moleculer-web/src/index.js:749:18)
    at Service.callAction (/Volumes/Boskysoft/work-hdd/recrutiment-smart/play/nodejs/moleculer-js/http-client/node_modules/moleculer-web/src/index.js:625:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Volumes/Boskysoft/work-hdd/recrutiment-smart/play/nodejs/moleculer-js/http-client/node_modules/moleculer-web/src/index.js:460:21
```

`/API: <= 500 GET /api/~node/services?withActions=true [+15.368 ms]`

**Comment by AndreMaz** [comment]
Can you please add the actual code to reproduce the issue?

**Comment by arun-prakash-fokus** [comment]
Steps to reproduce this issue:

1. Update your `greetings.service.js` as shown below
2. Run `npm run dev`
3. Check your services 
<img src="https://user-images.githubusercontent.com/25454690/109439263-e9d37b00-7a2d-11eb-91ff-10923cc89b6c.png"  width="50%">
4. Open your browser and navigate to http://localhost:3000/ 

**So far no issues**

Navigate to `Services` tab
![image](https://user-images.githubusercontent.com/25454690/109439436-9877bb80-7a2e-11eb-8f0e-1d1db6a82e53.png)

There are no services listed and in the console, you get the error messages described in the issue reported by @yogesh-rs 

```
// greetings.service.js
"use strict";

/**
 * @typedef {import('moleculer').Context} Context Moleculer's Context
 */

// https://github.com/moleculerjs/moleculer-http-client
const HTTPClientService = require('moleculer-http-client');

module.exports = {
	name: "greeter",

	mixins: [HTTPClientService],

	/**
	 * Settings
	 */
	settings: {

	},

	/**
	 * Dependencies
	 */
	dependencies: [],

	/**
	 * Actions
	 */
	actions: {

		/**
		 * Say a 'Hello' action.
		 *
		 * @returns
		 */
		hello: {
			rest: {
				method: "GET",
				path: "/hello"
			},
			async handler() {
				return this.hello();
			}
		},

		/**
		 * Welcome, a username
		 *
		 * @param {String} name - User name
		 */
		welcome: {
			rest: "/welcome",
			params: {
				name: "string"
			},
			/** @param {Context} ctx  */
			async handler(ctx) {
				return `Welcome, ${ctx.params.name}`;
			}
		}
	},

	/**
	 * Events
	 */
	events: {

	},

	/**
	 * Methods
	 */
	methods: {
		async hello() {

			const msg = {};
			msg.endpoint = this.settings.nifiEndpoint;

			this.broker.call("http.get", {
				url: "https://httpbin.org/json",
				opt: { responseType: "json" }
			})
				.then(res => broker.logger.info(res))
				.catch(error => broker.logger.error(error));
		},
	},

	/**
	 * Service created lifecycle event handler
	 */
	created() {

	},

	/**
	 * Service started lifecycle event handler
	 */
	async started() {

	},

	/**
	 * Service stopped lifecycle event handler
	 */
	async stopped() {

	}
};
```

**Comment by AndreMaz** [comment]
Thanks @arun-prakash-fokus I've fixed the issue and released it in `v0.4.1`

**Comment by arun-prakash-fokus** [comment]
Thank you for the quick fix. 

On another note, we have the actions from the `HTTPClientService` shown through the API gateway for the `greeter` service. Is this the expected behavior?

![image](https://user-images.githubusercontent.com/25454690/109500710-df010080-7a96-11eb-85c6-677fb5131bd8.png)

**Comment by AndreMaz** [comment]
Yes, by default all actions are public and visible.
However, you can mark them as private or even remove them, if necessary, by adapting the [method filtering example](https://github.com/moleculerjs/moleculer-http-client/blob/master/examples/select-http-methods/method-selector.mixin.js)
